str="";
str+="<form id=\"search\" action=\"http://www.google.com/custom\" method=\"get\"  name=\"search\" target=\"_blank\">";
str+="  <div style=\"float:left; width:18px;\"></div>";
str+="      <div id=\"searchTextDiv\">";
str+="        <input type=\"hidden\" name=\"cof1\" value=\"AH:center;AWFID:402f7fba780fe25f;\" />";
str+="        <input type=\"hidden\" name=\"domains\" value=\"sothink.com\" />";
str+="        <input type=\"hidden\" name=\"domains1\" value=\"www.sothink.com\" />";
str+="        <input type=\"hidden\" name=\"sitesearch\" value=\"sothink.com\" />";
str+="        <input id=\"q\" name=\"q\" type=\"text\" class=\"verdana10\" size=\"16\" />";
str+="      </div>";
str+="      <div style=\"float:left;\">";
str+="        <input name=\"image\" type=\"image\" id=\"submit\" src=\"/style/style_blue/images/btn-search.gif\" alt=\"GO\" style=\"width:30px; height:30px; border:none;\" />";
str+="      </div>";
str+="    </form>";
document.write(str);